#!/usr/bin/env python3
"""
Merge imported chemical data into chemical_db.py

Usage:
    python scripts/merge_chemical_db.py --input backend/app/data/chemical_db_imported.json
"""

import json
import argparse
from pathlib import Path


def generate_merge_code(imported: dict) -> str:
    """Generate Python code to merge imported data into chemical_db.py."""
    
    lines = []
    lines.append("# ═══════════════════════════════════════════════════════════════════")
    lines.append("# Imported compounds — auto-generated by import_chemicals.py")
    lines.append(f"# Total: {len(imported)} compounds")
    lines.append("# ═══════════════════════════════════════════════════════════════════")
    lines.append("")
    lines.append("IMPORTED_COMPOUNDS = {")
    
    for key, data in sorted(imported.items()):
        lines.append(f'    "{key}": {{')
        for k, v in data.items():
            if isinstance(v, str):
                lines.append(f'        "{k}": "{v}",')
            elif isinstance(v, (int, float)):
                lines.append(f'        "{k}": {v},')
            elif isinstance(v, bool):
                lines.append(f'        "{k}": {v},')
            elif v is None:
                lines.append(f'        "{k}": None,')
        lines.append("    },")
    
    lines.append("}")
    lines.append("")
    lines.append("# Merge into main database")
    lines.append("CHEMICAL_DATABASE.update(IMPORTED_COMPOUNDS)")
    
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Merge imported chemical data")
    parser.add_argument("--input", required=True, help="Input JSON file")
    parser.add_argument("--output", default="backend/app/data/chemical_db_imported.py", help="Output Python file")
    args = parser.parse_args()
    
    with open(args.input) as f:
        imported = json.load(f)
    
    code = generate_merge_code(imported)
    
    with open(args.output, "w") as f:
        f.write(code)
    
    print(f"✅ Generated {args.output} with {len(imported)} compounds")
    print(f"📝 Add this to chemical_db.py: from .chemical_db_imported import IMPORTED_COMPOUNDS")


if __name__ == "__main__":
    main()
